version: '3'
services:
  db:
    image: mysql:5.7.24
    volumes:
      - db-data:/var/lib/mysql
    env_file: docker/.env
  redis:
    image: redis:5.0.1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - gems_cache:/gems
    env_file: docker/.env
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - elasticsearch

volumes:
  db-data:
  gems_cache:
  elasticsearch:
